### ISSUE TITLE
Not running with jumpmarks

### ISSUE THREAD

**Issue by pavelzw** [weisJ/Mima#14]
I have Java version 1.8.0_191 and after I compile, it's not running when I run it with jumpmarks:

Here is my code:

LDC(0);
NOT();
STV(25);
LDC(24);
A: STV(26);
STIV(26);
ADD(25);
JMN(B);
JMP(A);
B: HALT();

**Comment by pavelzw** [comment]
I'm running on Mima 1.6

**Comment by weisJ** [comment]
This was caused by incompatibility of Java 11 with older versions. As of Java 11 the javaFX package was moved into its own distribution causing some files to be missing in newer JREs.
